services:
  db:
    image: mysql:8.0.32
    environment:
      MYSQL_HOST: "%"
      MYSQL_DATABASE: test
      MYSQL_USER: admin
      MYSQL_PASSWORD: passwd
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: passwd
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/initdb:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - backend
    healthcheck:  
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]  
      interval: 10s  
      timeout: 5s  
      retries: 5  

volumes:
  db_data:
    driver: local

networks:
  backend:
    driver: bridge
    ipam:
      driver: default

